---
##########################
# versions

ceph_version: {{cookiecutter.ceph_version}}

##########################
# helper

configure_cephclient: yes
configure_openstackclient: yes
configure_phpmyadmin: yes
configure_rally: yes
configure_sshconfig: yes

##########################
# cephclient

{% raw -%}
cephclient_keyring: "{{ lookup('file', '{{ configuration_directory }}/environments/infrastructure/files/ceph/ceph.client.admin.keyring') }}"
cephclient_keyring_name: client.admin
cephclient_mons:
  - FIXME
cephclient_cluster_fsid: "{{ ceph_cluster_fsid }}"
cephclient_groupname: manager
{%- endraw %}

##########################
# openstackclient

{% raw -%}
openstackclient_directory: "{{ configuration_directory }}/environments/openstack"
openstackclient_configuration_directory: "{{ configuration_directory }}/environments/openstack"
{%- endraw %}

##########################
# rally

{% raw -%}
rally_nginx_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"
{%- endraw %}

##########################
# phpmyadmin

{% raw -%}
phpmyadmin_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"
phpmyadmin_database_host: "{{ kolla_internal_vip_address }}"
{%- endraw %}

##########################
# mirror

configure_aptly: no
configure_nginx: no
configure_registry: no

# aptly

{% raw -%}
aptly_nginx_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"

aptly_repository_keys:
  - https://download.docker.com/linux/ubuntu/gpg
  - https://download.ceph.com/keys/release.asc

aptly_repositories:
  - name: ceph
    architecture: amd64
    distribution: "{{ ansible_distribution_release }}"
    repository: "https://download.ceph.com/debian-{{ ceph_version }} {{ ansible_distribution_release }} main"
  - name: docker
    architecture: amd64
    distribution: "{{ ansible_distribution_release }}"
    repository: "https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  - name: openstack
    architecture: amd64
    distribution: "{{ ansible_distribution_release }}"
    repository: "http://ubuntu-cloud.archive.canonical.com/ubuntu {{ ansible_distribution_release }}-updates/{{ openstack_version }} main"
  - name: "{{ ansible_distribution_release }}"
    architecture: amd64
    distribution: "{{ ansible_distribution_release }}"
    repository: "http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted universe multiverse"
  - name: "{{ ansible_distribution_release }}-backports"
    architecture: amd64
    distribution: "{{ ansible_distribution_release }}"
    repository: "http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
  - name: "{{ ansible_distribution_release }}-security"
    architecture: amd64
    distribution: "{{ ansible_distribution_release }}"
    repository: "http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security main restricted universe multiverse"
  - name: "{{ ansible_distribution_release }}-updates"
    architecture: amd64
    distribution: "{{ ansible_distribution_release }}"
    repository: "http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted universe multiverse"
{%- endraw %}

# registry

{% raw -%}
registry_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"
{%- endraw %}

# nginx

{% raw -%}
nginx_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"
{%- endraw %}

mirror_files_files:
  - url: https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
    dest: cirros-0.4.0-x86_64-disk.img
    checksum: "sha256:a8dd75ecffd4cdd96072d60c2237b448e0c8b2bc94d57f10fdbc8c481d9005b8"
  - url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
    dest: xenial-server-cloudimg-amd64-disk1.img
    checksum: "sha256:1cbcd7982061f60172fb90f2b08f5da155096d5c7d7979777a46cd36c722a15d"
  - url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
    dest: bionic-server-cloudimg-amd64-disk1.img
    checksum: "sha256:79387809763cdc12ea64dce5e9e6549127454847bebc206aae052d3e53822e91"
