---
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r test-requirements.txt
  - pip install -r requirements.txt

script:
  - cookiecutter --no-input .
  - yamllint -c .yamllint.yml cfg-customer

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
