---
##########################
# monitoring

{% raw -%}
monitoring_elasticsearch_host: "{{ kolla_internal_vip_address }}"
monitoring_grafana_host: "{{ kolla_internal_vip_address }}"
monitoring_prometheus_host: "{{ kolla_internal_vip_address }}"
{%- endraw %}

##########################
# prometheus

{% raw -%}
prometheus_host: "{{ hostvars[inventory_hostname]['ansible_' + prometheus_scraper_interface]['ipv4']['address'] }}"
{%- endraw %}

prometheus_scraper_ceph_target_host: FIXME
prometheus_scraper_ceph_target_port: 9100
prometheus_scraper_ceph_metrics_path: /metrics/ceph

prometheus_enable_alertmanager: false

##########################
# exporter

{% raw -%}
prometheus_exporter_cadvisor_host: "{{ hostvars[inventory_hostname]['ansible_' + prometheus_scraper_interface]['ipv4']['address'] }}"
prometheus_exporter_nginx_host: "{{ hostvars[inventory_hostname]['ansible_' + prometheus_scraper_interface]['ipv4']['address'] }}"
prometheus_exporter_node_host: "{{ hostvars[inventory_hostname]['ansible_' + prometheus_scraper_interface]['ipv4']['address'] }}"
{%- endraw %}

{% raw -%}
prometheus_exporter_elasticsearch_target_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"
prometheus_exporter_haproxy_target_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"
prometheus_exporter_mariadb_target_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"
prometheus_exporter_memcached_target_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"
prometheus_exporter_prometheus_target_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"
prometheus_exporter_rabbitmq_target_host: "{{ hostvars[inventory_hostname]['ansible_' + management_interface]['ipv4']['address'] }}"
{%- endraw %}

prometheus_exporter_haproxy_target_username: openstack

prometheus_exporter_ceph_enable: yes

prometheus_exporter_ceph_public_network: {{cookiecutter.ceph_network_frontend}}
{% raw -%}
prometheus_exporter_ceph_cluster_fsid: "{{ ceph_cluster_fsid }}"
prometheus_exporter_ceph_keyring_path: "{{ configuration_directory }}/environments/monitoring/files/ceph/ceph.client.admin.keyring"
{%- endraw %}

prometheus_exporter_ipmitool_minute: "*/5"
prometheus_exporter_ipmitool_groupname: ipmitool

prometheus_exporter_smartmon_minute: "*/5"
prometheus_exporter_smartmon_groupname: smartmon
