---
repository_version: {{cookiecutter.repository_version}}

##########################################################
# ansible

ansible_become: true
ansible_become_user: root

##########################################################
# images

kolla_base_distro: ubuntu
kolla_install_type: source
openstack_release: {{cookiecutter.openstack_version}}

##########################################################
# kolla

config_strategy: COPY_ALWAYS
{% raw -%}
node_custom_config: "{{ configuration_directory }}/environments/kolla/files/overlays
{%- endraw %}

##########################################################
# haproxy

kolla_internal_fqdn: {{cookiecutter.fqdn_internal}}
{%- if cookiecutter.fqdn_external != cookiecutter.fqdn_internal %}
kolla_external_fqdn: {{cookiecutter.fqdn_external}}
{%- endif %}

kolla_enable_tls_external: "yes"

haproxy_client_timeout: 5m
haproxy_server_timeout: 5m

##########################################################
# networking

# NOTE: The configuration of the network interfaces to be used should be done via the inventory.

##########################################################
# docker

docker_namespace: osism
docker_restart_policy_retry: 0

##########################################################
# openstack

# enable services
enable_cinder: "yes"
enable_cinder_backup: "yes"
enable_grafana: "yes"
enable_heat: "yes"

# disable services
enable_chrony: "no"

# generic

# NOTE: This has to be "False", not "false"!
openstack_logging_debug: "False"
openstack_service_workers: 1

# logging
enable_central_logging: "yes"

# horizon
horizon_backend_database: "yes"

# keystone
keystone_token_provider: "fernet"

# neutron
neutron_plugin_agent: "openvswitch"

# nova
nova_console: novnc

##########################################################
# external ceph

enable_ceph: "no"

cinder_backend_ceph: "yes"
glance_backend_ceph: "yes"
nova_backend_ceph: "yes"

cinder_backup_driver: "ceph"

# NOTE: public_network from environments/ceph/configuration.yml
ceph_public_network: {{cookiecutter.ceph_network_frontend}}

##########################################################
# other
